# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 2
  no-warn: 1
  no-debug: 1
  no-ids: 2
  hex-notation:
    - 2
    -
      style: lowercase
  indentation:
    - 0
    -
      size: 4
  leading-zero: 2
  # no-color-literals: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  # variable-for-property:
  #   - 2
  #   -
  #     properties:
  #       - color
  zero-unit: 2
